using System;
using System.Collections.Generic;

namespace CoreAPI.DatabaseModels
{
    public partial class Clientuser
    {
        public int Nclientuserid { get; set; }
        public int? Nclientlocationid { get; set; }
        public string Cuserid { get; set; }
        public string Cfname { get; set; }
        public string Clname { get; set; }
        public string Ctitle { get; set; }
        public string Cemail { get; set; }
        public string Ctel { get; set; }
        public string Ctelext { get; set; }
        public string Cfax { get; set; }
        public string Cttdnumber { get; set; }
        public string Curl { get; set; }
        public string Caddress { get; set; }
        public string Caddress2 { get; set; }
        public string Ccity { get; set; }
        public string Cstate { get; set; }
        public string Czipcode { get; set; }
        public string Ccountry { get; set; }
        public int? Nlevelid { get; set; }
        public string Clevelcode { get; set; }
        public string Caccessgroup { get; set; }
        public string Cesignature { get; set; }
        public bool? Lvendorlisting { get; set; }
        public bool? Lfirsttimelogin { get; set; }
        public short? Nvendorselectoption { get; set; }
        public short? NvendorselectoptionProject { get; set; }
        public bool? Lapproveinsidetimecard { get; set; }
        public int? Napprovalmethod { get; set; }
        public bool? Lchangeapproval { get; set; }
        public bool? Lhidevendornamehiringproccess { get; set; }
        public bool? Lblockemailfromvendor { get; set; }
        public bool? Ldisablebillrate { get; set; }
        public bool? Ldisablepayrate { get; set; }
        public DateTime? Dlastpasswordupdate { get; set; }
        public bool? Lhidepayrate { get; set; }
        public bool? Lhidebillrate { get; set; }
        public bool? Lhidejobexpense { get; set; }
        public bool? Lhidejobadditionaltimecardspend { get; set; }
        public bool? Lhidejobestimate { get; set; }
        public bool? Lhideassgpay { get; set; }
        public bool? Lhideassgbill { get; set; }
        public bool? Lhideassginclusive { get; set; }
        public bool? Lhideassgexpense { get; set; }
        public bool? Lhideassgadditionaltimecardspend { get; set; }
        public bool? Lhideassgestimate { get; set; }
        public bool? Lhidemarkup { get; set; }
        public bool? Ldisablemarkup { get; set; }
        public bool? Lpopupmessage { get; set; }
        public bool? Lbillcontact { get; set; }
        public int? Nbillcontactid { get; set; }
        public bool? Lselfregister { get; set; }
        public bool? Lemailperschedule { get; set; }
        public DateTime? Dgetemail1 { get; set; }
        public DateTime? Dgetemail2 { get; set; }
        public DateTime? Dgetemail3 { get; set; }
        public bool? Lreportbasedonhirearchy { get; set; }
        public int? Nhierarchyreporttoid { get; set; }
        public string Corganizationcode { get; set; }
        public bool? Ldenytimecardaprroval { get; set; }
        public bool? Ldisablespecialbill { get; set; }
        public bool? Ldisableworkdaysrequest { get; set; }
        public bool? Lenableskilljobtitlesearch { get; set; }
        public bool? Ldisableassignmentextension { get; set; }
        public bool? Ldisableassignmentratechange { get; set; }
        public bool? Lnotallowcreatejob { get; set; }
        public bool? Lreportscheduling { get; set; }
        public DateTime? Daccepttermsconditions { get; set; }
        public bool? Llocked { get; set; }
        public bool? Lclientadmin { get; set; }
        public bool? Lworklocationcode { get; set; }
        public string Csbstring { get; set; }
        public bool? Lblocksystememail { get; set; }
        public bool? Lallowzerobillreq { get; set; }
        public bool? Lshowassignmentudf { get; set; }
        public bool? Lnotallowmodifytimecard { get; set; }
        public bool? Lnotallowmodifyexpense { get; set; }
        public bool? Ldisablemodifytcproxy { get; set; }
        public bool? Ldisablemodifyjobproxy { get; set; }
        public bool? Ldisablemodifyassignmentproxy { get; set; }
        public bool? Lhideresubmitorder { get; set; }
        public bool? Lhidereplacement { get; set; }
        public bool? Lsso { get; set; }
        public bool? Lopenbidadmin { get; set; }
        public bool? Lhideduplicatejob { get; set; }
        public bool? Ldisablemodifysbprofile { get; set; }
        public bool? Lshowjobtitleadvancesearch { get; set; }
        public bool? Lhidejobexempt { get; set; }
        public bool? Lallowmodifyjobinfo { get; set; }
        public bool? Lonepagereqcreation { get; set; }
        public bool? Lonepagereqcreationnobill { get; set; }
        public bool? Lreqapprovalbymobile { get; set; }
        public bool? Lcontractadditionaluser { get; set; }
        public bool? Lshowclassificationrecommendation { get; set; }
        public bool? LshowclassificationrecommendationNonbill { get; set; }
        public bool? LshowclassificationrecommendationProject { get; set; }
        public bool? LshowclassificationrecommendationSow { get; set; }
        public bool? Ldisplayallvendorlocation { get; set; }
        public bool? LdisplayallvendorlocationProject { get; set; }
        public bool? Lenablecreateproject { get; set; }
        public bool? Lenablecreatesow { get; set; }
        public int? Ndefaultlanguageid { get; set; }
        public int? Ndefaulttimezoneid { get; set; }
        public int? Ntimecardapprovaltype { get; set; }
        public bool? Lactive { get; set; }
        public bool? LchangeapprovalProject { get; set; }
        public string Cssouserid { get; set; }
        public DateTime? Dlasttimelogin { get; set; }
        public string Cpasswordtype { get; set; }
        public int? Npasswordattempt { get; set; }
        public DateTime? Dlocked { get; set; }
        public byte[] Cpassword { get; set; }
        public byte[] Coldpassword1 { get; set; }
        public byte[] Coldpassword2 { get; set; }
        public byte[] Coldpassword3 { get; set; }
        public byte[] Coldpassword4 { get; set; }
        public byte[] Coldpassword5 { get; set; }
        public bool? Lhidenegotiaterate { get; set; }
        public bool? Liccapprovaluser { get; set; }
        public int? Nmodifiedbywho { get; set; }
        public int? Nmodifiedby { get; set; }
        public DateTime? Dmodified { get; set; }
        public int? Ncreatedbywho { get; set; }
        public int? Ncreatedby { get; set; }
        public DateTime? Dcreated { get; set; }
        public bool? Lhidepreferbillrate { get; set; }
        public bool? Ldisablepreferbillrate { get; set; }
        public bool? Ldisableassignmentadditionalexpense { get; set; }
        public int? Ndirectsend { get; set; }
        public int? Ndirectsendproject { get; set; }
        public string Cpagetheme { get; set; }
        public bool? Lshowclientcandidatewizard { get; set; }
    }
}
